package com.inventoryApplication.view;

import com.inventoryApplication.model.ContractModel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 * 
 * 
 */

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    CardLayout cardLayout;
       private List<ContractModel> ContractList;
    public Dashboard() {
        initComponents();
        initializeLayout();
        setDefaultActiveButton();
        initializeData();
       
    }
    private void setDefaultActiveButton() {
    activeButton = DashBoardButton;  // Make DashboardButton active by default
    setBtnColor(DashBoardButton);   // Apply active button color
    activeButton.setBorder(BorderFactory.createMatteBorder(0, 5, 0, 0, new Color(237, 240, 242)));
    loadScreen("DashBoardScreen");  // Load default screen
}
      private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        pnlCards.setLayout(cardLayout);

     
        pnlCards.add(DashBoardPanel, "DashBoardScreen");
        pnlCards.add(InstockPanel, "InStockScreen");
        pnlCards.add(ProductPanel, "ProductScreen");
        pnlCards.add(ContractPanel, "ContractScreen");
        pnlCards.add(OrdersPanel, "OrdersScreen");
        pnlCards.add(SuppliersPanel, "SuppliersScreen");

        // Start with the loading screen
        cardLayout.show(pnlCards, "DashBoardScreen");
    }
       private void addContract(ContractModel contract) {
        ContractList.add(contract);
        DefaultTableModel model = (DefaultTableModel) tableContractDashboard.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tableContractDashboard1.getModel();
        model2.addRow(new Object[]{contract.getContractId(),contract.getContractTitle(),contract.getContractLocation(),contract.getContractStartDate(),contract.getContractExpectedEndDate(),contract.getContractStatus(),contract.getContractValue(),contract.getClientName(),contract.getScopeOfWork()});

        model.addRow(new Object[]{contract.getContractId(),contract.getContractTitle(),contract.getContractLocation(),contract.getContractStartDate(),contract.getContractExpectedEndDate(),contract.getContractStatus(),contract.getContractValue(),contract.getClientName(),contract.getScopeOfWork()
        });
    }
    private void initializeData() {
        ContractList = new ArrayList();
        addContract(new ContractModel(1, "Construction of gate", "baluwatar", LocalDate.parse("2024-12-09"),LocalDate.parse("2024-12-14"),"Pending",22000,"Suya pratap Singh","Make a good looking gate for new built house"));
        addContract(new ContractModel(2, "Construction of Railing", "baluwatar", LocalDate.parse("2024-12-03"),LocalDate.parse("2024-12-10"),"Completed",60000,"Manoj Khadka","Make a good looking railing for new built house"));
        addContract(new ContractModel(1, "Construction of gate", "baluwatar", LocalDate.parse("2024-12-09"),LocalDate.parse("2024-12-14"),"Pending",22000,"Suya pratap Singh","Make a good looking gate for new built house"));
        addContract(new ContractModel(2, "Construction of Railing", "baluwatar", LocalDate.parse("2024-12-03"),LocalDate.parse("2024-12-10"),"Completed",60000,"Manoj Khadka","Make a good looking railing for new built house"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavBar = new javax.swing.JPanel();
        MainLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addProductBtn = new RoundedPanel(50,new Color(194,72,34));
        addProductText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addContractBtn = new RoundedPanel(50,new Color(44,44,44));
        addProductText1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addStockBtn = new RoundedPanel(50,new Color(56,183,53));
        addProductText2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        SideMenu = new javax.swing.JPanel();
        DashBoardButton = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JLabel();
        DashboardText = new javax.swing.JLabel();
        InStockButton = new javax.swing.JPanel();
        MenuIcon2 = new javax.swing.JLabel();
        InStockText = new javax.swing.JLabel();
        ProductButton = new javax.swing.JPanel();
        MenuIcon3 = new javax.swing.JLabel();
        ProductText = new javax.swing.JLabel();
        ContractButton = new javax.swing.JPanel();
        MenuIcon4 = new javax.swing.JLabel();
        ContractText = new javax.swing.JLabel();
        OrderButton = new javax.swing.JPanel();
        MenuIcon5 = new javax.swing.JLabel();
        OrderText = new javax.swing.JLabel();
        SupplierButton = new javax.swing.JPanel();
        MenuIcon6 = new javax.swing.JLabel();
        SupplierText = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        InstockPanel = new javax.swing.JScrollPane();
        ProductPanel = new javax.swing.JScrollPane();
        OrdersPanel = new javax.swing.JScrollPane();
        SuppliersPanel = new javax.swing.JScrollPane();
        ContractPanel = new javax.swing.JScrollPane();
        pnlContractMain = new javax.swing.JPanel();
        pnlDataDisplayParent1 = new javax.swing.JPanel();
        addContractsPanel = new RoundedPanel(40,Color.white);
        addContractText = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtContractTitle = new javax.swing.JTextField();
        txtContractId = new javax.swing.JTextField();
        txtContractLocation = new javax.swing.JTextField();
        txtContractExpectedEndDate = new javax.swing.JTextField();
        txtContractStatus = new javax.swing.JTextField();
        txtContractValue = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtScopeOfWork = new javax.swing.JTextArea();
        addContractBtn1 = new RoundedPanel(50,new Color(44,44,44));
        addProductText3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PendingContractsDisplay2 = new RoundedPanel(40,Color.WHITE);
        totalPurchaseText6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableContractDashboard1 = new javax.swing.JTable();
        DashBoardPanel = new javax.swing.JScrollPane();
        DashBoardScreen = new javax.swing.JPanel();
        pnlDisplayParent = new javax.swing.JPanel();
        displayPanel3 = new RoundedPanel(40,Color.WHITE);
        revenueText6 = new javax.swing.JLabel();
        totalPurchaseText2 = new javax.swing.JLabel();
        displayPanel1 = new RoundedPanel(40,Color.WHITE);
        revenueText3 = new javax.swing.JLabel();
        totalPurchaseText = new javax.swing.JLabel();
        displayPanel2 = new RoundedPanel(40,Color.WHITE);
        revenueText5 = new javax.swing.JLabel();
        totalPurchaseText3 = new javax.swing.JLabel();
        pnlDataDisplayParent = new javax.swing.JPanel();
        PendingContractsDisplay1 = new RoundedPanel(40,Color.WHITE);
        totalPurchaseText4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableContractDashboard = new javax.swing.JTable();
        NewOrdersDisplayPanel = new RoundedPanel(40,Color.WHITE);
        totalPurchaseText1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NewOrdersDisplayPanel1 = new RoundedPanel(40,Color.WHITE);
        totalPurchaseText5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName("Dashboard"); // NOI18N

        NavBar.setBackground(new java.awt.Color(255, 255, 255));

        MainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/MainLogo.png"))); // NOI18N
        MainLogo.setText("jLabel1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/searchIcon.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(243, 243, 243));
        jTextField1.setColumns(10);
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        addProductBtn.setBackground(null);
        addProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductBtnMouseExited(evt);
            }
        });

        addProductText.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        addProductText.setForeground(new java.awt.Color(255, 255, 255));
        addProductText.setText("   Add Product");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("+");

        javax.swing.GroupLayout addProductBtnLayout = new javax.swing.GroupLayout(addProductBtn);
        addProductBtn.setLayout(addProductBtnLayout);
        addProductBtnLayout.setHorizontalGroup(
            addProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductBtnLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        addProductBtnLayout.setVerticalGroup(
            addProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(addProductText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addContractBtn.setBackground(null);
        addContractBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addContractBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addContractBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addContractBtnMouseExited(evt);
            }
        });

        addProductText1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        addProductText1.setForeground(new java.awt.Color(255, 255, 255));
        addProductText1.setText("   Add Contract");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("+");

        javax.swing.GroupLayout addContractBtnLayout = new javax.swing.GroupLayout(addContractBtn);
        addContractBtn.setLayout(addContractBtnLayout);
        addContractBtnLayout.setHorizontalGroup(
            addContractBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractBtnLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addProductText1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        addContractBtnLayout.setVerticalGroup(
            addContractBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(addProductText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addStockBtn.setBackground(null);
        addStockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStockBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStockBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStockBtnMouseExited(evt);
            }
        });

        addProductText2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        addProductText2.setForeground(new java.awt.Color(255, 255, 255));
        addProductText2.setText("   Add Stock");

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("+");

        javax.swing.GroupLayout addStockBtnLayout = new javax.swing.GroupLayout(addStockBtn);
        addStockBtn.setLayout(addStockBtnLayout);
        addStockBtnLayout.setHorizontalGroup(
            addStockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStockBtnLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductText2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        addStockBtnLayout.setVerticalGroup(
            addStockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(addProductText2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(addProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addContractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(MainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addContractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addProductBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerSize(0);

        SideMenu.setBackground(new java.awt.Color(37, 38, 58));
        SideMenu.setMaximumSize(new java.awt.Dimension(113, 934));
        SideMenu.setMinimumSize(new java.awt.Dimension(113, 934));
        SideMenu.setName("DashBoardIcon"); // NOI18N
        SideMenu.setPreferredSize(new java.awt.Dimension(113, 934));

        DashBoardButton.setBackground(new java.awt.Color(37, 38, 58));
        DashBoardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBoardButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashBoardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashBoardButtonMouseExited(evt);
            }
        });

        MenuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon.setText("jLabel1");

        DashboardText.setBackground(new java.awt.Color(255, 255, 255));
        DashboardText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        DashboardText.setForeground(new java.awt.Color(255, 255, 255));
        DashboardText.setText("Dashboard");

        javax.swing.GroupLayout DashBoardButtonLayout = new javax.swing.GroupLayout(DashBoardButton);
        DashBoardButton.setLayout(DashBoardButtonLayout);
        DashBoardButtonLayout.setHorizontalGroup(
            DashBoardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardButtonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(MenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        DashBoardButtonLayout.setVerticalGroup(
            DashBoardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardButtonLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(MenuIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashboardText)
                .addGap(6, 6, 6))
        );

        InStockButton.setBackground(new java.awt.Color(37, 38, 58));
        InStockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InStockButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InStockButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InStockButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InStockButtonMousePressed(evt);
            }
        });

        MenuIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon2.setText("jLabel1");

        InStockText.setBackground(new java.awt.Color(255, 255, 255));
        InStockText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        InStockText.setForeground(new java.awt.Color(255, 255, 255));
        InStockText.setText("In-Stock");

        javax.swing.GroupLayout InStockButtonLayout = new javax.swing.GroupLayout(InStockButton);
        InStockButton.setLayout(InStockButtonLayout);
        InStockButtonLayout.setHorizontalGroup(
            InStockButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InStockButtonLayout.createSequentialGroup()
                .addGroup(InStockButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InStockButtonLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(InStockText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InStockButtonLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(MenuIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        InStockButtonLayout.setVerticalGroup(
            InStockButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InStockButtonLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(MenuIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InStockText)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ProductButton.setBackground(new java.awt.Color(37, 38, 58));
        ProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductButtonMouseExited(evt);
            }
        });

        MenuIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon3.setText("jLabel1");

        ProductText.setBackground(new java.awt.Color(255, 255, 255));
        ProductText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        ProductText.setForeground(new java.awt.Color(255, 255, 255));
        ProductText.setText("Products");

        javax.swing.GroupLayout ProductButtonLayout = new javax.swing.GroupLayout(ProductButton);
        ProductButton.setLayout(ProductButtonLayout);
        ProductButtonLayout.setHorizontalGroup(
            ProductButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductButtonLayout.createSequentialGroup()
                .addGroup(ProductButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductButtonLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(MenuIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductButtonLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ProductText)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        ProductButtonLayout.setVerticalGroup(
            ProductButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(MenuIcon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductText)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ContractButton.setBackground(new java.awt.Color(37, 38, 58));
        ContractButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContractButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContractButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContractButtonMouseExited(evt);
            }
        });

        MenuIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon4.setText("jLabel1");

        ContractText.setBackground(new java.awt.Color(255, 255, 255));
        ContractText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        ContractText.setForeground(new java.awt.Color(255, 255, 255));
        ContractText.setText("Contracts");

        javax.swing.GroupLayout ContractButtonLayout = new javax.swing.GroupLayout(ContractButton);
        ContractButton.setLayout(ContractButtonLayout);
        ContractButtonLayout.setHorizontalGroup(
            ContractButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractButtonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ContractButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContractText)
                    .addGroup(ContractButtonLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(MenuIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        ContractButtonLayout.setVerticalGroup(
            ContractButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(MenuIcon4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContractText)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        OrderButton.setBackground(new java.awt.Color(37, 38, 58));
        OrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderButtonMouseExited(evt);
            }
        });

        MenuIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon5.setText("jLabel1");

        OrderText.setBackground(new java.awt.Color(255, 255, 255));
        OrderText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        OrderText.setForeground(new java.awt.Color(255, 255, 255));
        OrderText.setText("Orders");

        javax.swing.GroupLayout OrderButtonLayout = new javax.swing.GroupLayout(OrderButton);
        OrderButton.setLayout(OrderButtonLayout);
        OrderButtonLayout.setHorizontalGroup(
            OrderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderButtonLayout.createSequentialGroup()
                .addGroup(OrderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderButtonLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(MenuIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrderButtonLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(OrderText)))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        OrderButtonLayout.setVerticalGroup(
            OrderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(MenuIcon5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderText)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        SupplierButton.setBackground(new java.awt.Color(37, 38, 58));
        SupplierButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupplierButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupplierButtonMouseExited(evt);
            }
        });

        MenuIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/InStockIcon.png"))); // NOI18N
        MenuIcon6.setText("jLabel1");

        SupplierText.setBackground(new java.awt.Color(255, 255, 255));
        SupplierText.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        SupplierText.setForeground(new java.awt.Color(255, 255, 255));
        SupplierText.setText("Suppliers");

        javax.swing.GroupLayout SupplierButtonLayout = new javax.swing.GroupLayout(SupplierButton);
        SupplierButton.setLayout(SupplierButtonLayout);
        SupplierButtonLayout.setHorizontalGroup(
            SupplierButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierButtonLayout.createSequentialGroup()
                .addGroup(SupplierButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SupplierButtonLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(MenuIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SupplierButtonLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(SupplierText)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        SupplierButtonLayout.setVerticalGroup(
            SupplierButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(MenuIcon6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupplierText)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SideMenuLayout = new javax.swing.GroupLayout(SideMenu);
        SideMenu.setLayout(SideMenuLayout);
        SideMenuLayout.setHorizontalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashBoardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContractButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideMenuLayout.setVerticalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DashBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(InStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ContractButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(SupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(SideMenu);

        pnlCards.setLayout(new java.awt.CardLayout());

        InstockPanel.setBorder(null);
        pnlCards.add(InstockPanel, "card3");

        ProductPanel.setBorder(null);
        pnlCards.add(ProductPanel, "card4");

        OrdersPanel.setBorder(null);
        pnlCards.add(OrdersPanel, "card5");

        SuppliersPanel.setBorder(null);
        pnlCards.add(SuppliersPanel, "card6");

        ContractPanel.setBorder(null);

        pnlContractMain.setBackground(new java.awt.Color(237, 240, 242));

        pnlDataDisplayParent1.setBackground(new java.awt.Color(237, 240, 242));

        javax.swing.GroupLayout pnlDataDisplayParent1Layout = new javax.swing.GroupLayout(pnlDataDisplayParent1);
        pnlDataDisplayParent1.setLayout(pnlDataDisplayParent1Layout);
        pnlDataDisplayParent1Layout.setHorizontalGroup(
            pnlDataDisplayParent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        pnlDataDisplayParent1Layout.setVerticalGroup(
            pnlDataDisplayParent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        addContractsPanel.setBackground(null);

        addContractText.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        addContractText.setForeground(new java.awt.Color(194, 72, 34));
        addContractText.setText("Add Contracts");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        txtContractTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Title:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractTitleActionPerformed(evt);
            }
        });

        txtContractId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Id:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractIdActionPerformed(evt);
            }
        });

        txtContractLocation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Location:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractLocationActionPerformed(evt);
            }
        });

        txtContractExpectedEndDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Expected End Date:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractExpectedEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractExpectedEndDateActionPerformed(evt);
            }
        });

        txtContractStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Status:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractStatusActionPerformed(evt);
            }
        });

        txtContractValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contract Value:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtContractValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractValueActionPerformed(evt);
            }
        });

        txtClientName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Name:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 14))); // NOI18N
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });

        txtScopeOfWork.setColumns(20);
        txtScopeOfWork.setRows(5);
        txtScopeOfWork.setBorder(null);
        jScrollPane1.setViewportView(txtScopeOfWork);

        addContractBtn1.setBackground(null);
        addContractBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addContractBtn1MouseClicked(evt);
            }
        });

        addProductText3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        addProductText3.setForeground(new java.awt.Color(255, 255, 255));
        addProductText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addProductText3.setText("   Add Contract");

        javax.swing.GroupLayout addContractBtn1Layout = new javax.swing.GroupLayout(addContractBtn1);
        addContractBtn1.setLayout(addContractBtn1Layout);
        addContractBtn1Layout.setHorizontalGroup(
            addContractBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractBtn1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(addProductText3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addContractBtn1Layout.setVerticalGroup(
            addContractBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addProductText3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setText("Scope Of Work:");

        javax.swing.GroupLayout addContractsPanelLayout = new javax.swing.GroupLayout(addContractsPanel);
        addContractsPanel.setLayout(addContractsPanelLayout);
        addContractsPanelLayout.setHorizontalGroup(
            addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                        .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(addContractsPanelLayout.createSequentialGroup()
                                .addComponent(txtContractExpectedEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContractValue, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addContractsPanelLayout.createSequentialGroup()
                                .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContractId, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(txtContractLocation)
                                    .addComponent(addContractText, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtContractStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(txtContractTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addContractBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        addContractsPanelLayout.setVerticalGroup(
            addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addContractText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                        .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContractId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContractTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContractLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContractStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addContractsPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(addContractsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContractExpectedEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContractValue, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContractsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addContractBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PendingContractsDisplay2.setBackground(null);
        PendingContractsDisplay2.setBorder(null);
        PendingContractsDisplay2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPurchaseText6.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText6.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText6.setText("Contract List:");
        PendingContractsDisplay2.add(totalPurchaseText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 271, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        PendingContractsDisplay2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1120, 19));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);

        tableContractDashboard1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract Id", "Contract Title", "Contract Location", "Contract Start Date", "Contract End Date", "Contract Status", "Contract value ", "Client Name", "Scope Of Work"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableContractDashboard1);

        PendingContractsDisplay2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1120, 90));

        javax.swing.GroupLayout pnlContractMainLayout = new javax.swing.GroupLayout(pnlContractMain);
        pnlContractMain.setLayout(pnlContractMainLayout);
        pnlContractMainLayout.setHorizontalGroup(
            pnlContractMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContractMainLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(pnlContractMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PendingContractsDisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addContractsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(pnlContractMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContractMainLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDataDisplayParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlContractMainLayout.setVerticalGroup(
            pnlContractMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContractMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PendingContractsDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(addContractsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1522, Short.MAX_VALUE))
            .addGroup(pnlContractMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContractMainLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDataDisplayParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ContractPanel.setViewportView(pnlContractMain);

        pnlCards.add(ContractPanel, "card7");

        DashBoardPanel.setBorder(null);

        DashBoardScreen.setBackground(new java.awt.Color(237, 240, 242));

        pnlDisplayParent.setBackground(new java.awt.Color(237, 240, 242));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5);
        flowLayout1.setAlignOnBaseline(true);
        pnlDisplayParent.setLayout(flowLayout1);

        displayPanel3.setBackground(null);
        displayPanel3.setBorder(null);

        revenueText6.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        revenueText6.setForeground(new java.awt.Color(194, 72, 34));
        revenueText6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/cardLogo.png"))); // NOI18N

        totalPurchaseText2.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText2.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText2.setText("Income");

        javax.swing.GroupLayout displayPanel3Layout = new javax.swing.GroupLayout(displayPanel3);
        displayPanel3.setLayout(displayPanel3Layout);
        displayPanel3Layout.setHorizontalGroup(
            displayPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(displayPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revenueText6)
                    .addComponent(totalPurchaseText2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        displayPanel3Layout.setVerticalGroup(
            displayPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(totalPurchaseText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(revenueText6)
                .addGap(29, 29, 29))
        );

        pnlDisplayParent.add(displayPanel3);

        displayPanel1.setBackground(null);
        displayPanel1.setBorder(null);

        revenueText3.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        revenueText3.setForeground(new java.awt.Color(194, 72, 34));
        revenueText3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/cardLogo.png"))); // NOI18N

        totalPurchaseText.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText.setText("Revenue");

        javax.swing.GroupLayout displayPanel1Layout = new javax.swing.GroupLayout(displayPanel1);
        displayPanel1.setLayout(displayPanel1Layout);
        displayPanel1Layout.setHorizontalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revenueText3)
                    .addComponent(totalPurchaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        displayPanel1Layout.setVerticalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(totalPurchaseText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(revenueText3)
                .addGap(29, 29, 29))
        );

        pnlDisplayParent.add(displayPanel1);

        displayPanel2.setBackground(null);
        displayPanel2.setBorder(null);

        revenueText5.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        revenueText5.setForeground(new java.awt.Color(194, 72, 34));
        revenueText5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventoryApplication/resources/cardLogo.png"))); // NOI18N

        totalPurchaseText3.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText3.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText3.setText("Total Purchase");

        javax.swing.GroupLayout displayPanel2Layout = new javax.swing.GroupLayout(displayPanel2);
        displayPanel2.setLayout(displayPanel2Layout);
        displayPanel2Layout.setHorizontalGroup(
            displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPurchaseText3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revenueText5))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        displayPanel2Layout.setVerticalGroup(
            displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPurchaseText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(revenueText5)
                .addGap(29, 29, 29))
        );

        pnlDisplayParent.add(displayPanel2);

        pnlDataDisplayParent.setBackground(new java.awt.Color(237, 240, 242));
        pnlDataDisplayParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PendingContractsDisplay1.setBackground(null);
        PendingContractsDisplay1.setBorder(null);
        PendingContractsDisplay1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPurchaseText4.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText4.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText4.setText("Pending Contracts");
        PendingContractsDisplay1.add(totalPurchaseText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 271, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        PendingContractsDisplay1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1120, 19));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        tableContractDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract Id", "Contract Title", "Contract Location", "Contract Start Date", "Contract End Date", "Contract Status", "Contract value ", "Client Name", "Scope Of Work"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableContractDashboard);

        PendingContractsDisplay1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1120, 90));

        pnlDataDisplayParent.add(PendingContractsDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 1160, 210));

        NewOrdersDisplayPanel.setBackground(null);
        NewOrdersDisplayPanel.setBorder(null);
        NewOrdersDisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPurchaseText1.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText1.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText1.setText("New Orders");
        NewOrdersDisplayPanel.add(totalPurchaseText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 271, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        NewOrdersDisplayPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1120, 19));

        NewOrdersDisplayPanel1.setBackground(null);
        NewOrdersDisplayPanel1.setBorder(null);
        NewOrdersDisplayPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPurchaseText5.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        totalPurchaseText5.setForeground(new java.awt.Color(194, 72, 34));
        totalPurchaseText5.setText("New Orders");
        NewOrdersDisplayPanel1.add(totalPurchaseText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 271, -1));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        NewOrdersDisplayPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1120, 19));

        javax.swing.GroupLayout DashBoardScreenLayout = new javax.swing.GroupLayout(DashBoardScreen);
        DashBoardScreen.setLayout(DashBoardScreenLayout);
        DashBoardScreenLayout.setHorizontalGroup(
            DashBoardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardScreenLayout.createSequentialGroup()
                .addGroup(DashBoardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashBoardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlDataDisplayParent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DashBoardScreenLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlDisplayParent, javax.swing.GroupLayout.PREFERRED_SIZE, 1326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DashBoardScreenLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(DashBoardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewOrdersDisplayPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewOrdersDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1438, Short.MAX_VALUE))
        );
        DashBoardScreenLayout.setVerticalGroup(
            DashBoardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardScreenLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlDisplayParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(pnlDataDisplayParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(NewOrdersDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewOrdersDisplayPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        DashBoardPanel.setViewportView(DashBoardScreen);

        pnlCards.add(DashBoardPanel, "card10");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void loadScreen(String screenName) {
        cardLayout.show(pnlCards, screenName);
    }
  private void setBtnColor(JPanel btn) {
         btn.setBackground(new Color(194, 72, 34)); 
    }
     private void setInitialBtnColor(JPanel btn) {
         btn.setBackground( new Color(37, 38, 58)); 
    }
     
     private JPanel activeButton = null;
    
     private void setActiveButton(JPanel btn) {
   
       
         
        if (activeButton != null && activeButton != btn) {
            setInitialBtnColor(activeButton);
            activeButton.setBorder(BorderFactory.createEmptyBorder());
        }
        activeButton = btn;
        setBtnColor(activeButton);
         activeButton.setBorder(BorderFactory.createMatteBorder(0, 5, 0, 0, new Color(237, 240, 242)));
}
   
    private void SupplierButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierButtonMouseClicked
        loadScreen("SuppliersScreen");
        setActiveButton(SupplierButton);
        
    }//GEN-LAST:event_SupplierButtonMouseClicked

    private void OrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseClicked
        loadScreen("OrdersScreen");
        setActiveButton(OrderButton);
        
    }//GEN-LAST:event_OrderButtonMouseClicked

    private void ContractButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContractButtonMouseClicked
        loadScreen("ContractScreen");
        setActiveButton(ContractButton);
        
    }//GEN-LAST:event_ContractButtonMouseClicked

    private void ProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButtonMouseClicked
        loadScreen("ProductScreen");
         setActiveButton(ProductButton);
        
    }//GEN-LAST:event_ProductButtonMouseClicked

    private void InStockButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InStockButtonMousePressed

    }//GEN-LAST:event_InStockButtonMousePressed

    private void InStockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InStockButtonMouseClicked
        loadScreen("InStockScreen");
        setActiveButton(InStockButton);
        
    }//GEN-LAST:event_InStockButtonMouseClicked

    private void DashBoardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardButtonMouseClicked
        loadScreen("DashBoardScreen");
        setActiveButton(DashBoardButton);
           
    }//GEN-LAST:event_DashBoardButtonMouseClicked

    private void DashBoardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardButtonMouseEntered
        // TODO add your handling code here:
          if (activeButton != DashBoardButton) {
        setBtnColor(DashBoardButton);
    }
        
    }//GEN-LAST:event_DashBoardButtonMouseEntered

    private void InStockButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InStockButtonMouseEntered
            if (activeButton != InStockButton) {
        setBtnColor(InStockButton);
    }
    }//GEN-LAST:event_InStockButtonMouseEntered

    private void ProductButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButtonMouseEntered
    if (activeButton != ProductButton) {
        setBtnColor(ProductButton);
    }
    }//GEN-LAST:event_ProductButtonMouseEntered

    private void ContractButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContractButtonMouseEntered
        if (activeButton != ContractButton) {
        setBtnColor(ContractButton);
    }
    }//GEN-LAST:event_ContractButtonMouseEntered

    private void OrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseEntered
            if (activeButton != OrderButton) {
        setBtnColor(OrderButton);
    }
    }//GEN-LAST:event_OrderButtonMouseEntered

    private void SupplierButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierButtonMouseEntered
              if (activeButton != SupplierButton) {
        setBtnColor(SupplierButton);
    }
    }//GEN-LAST:event_SupplierButtonMouseEntered

    private void DashBoardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardButtonMouseExited
       if (activeButton != DashBoardButton) {
        setInitialBtnColor(DashBoardButton);
    }
    }//GEN-LAST:event_DashBoardButtonMouseExited

    private void InStockButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InStockButtonMouseExited
      if (activeButton != InStockButton) {
        setInitialBtnColor(InStockButton);
    }
    }//GEN-LAST:event_InStockButtonMouseExited

    private void ProductButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButtonMouseExited
      if (activeButton != ProductButton) {
        setInitialBtnColor(ProductButton);
    }
    }//GEN-LAST:event_ProductButtonMouseExited

    private void ContractButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContractButtonMouseExited
          if (activeButton != ContractButton) {
        setInitialBtnColor(ContractButton);
    }
    }//GEN-LAST:event_ContractButtonMouseExited

    private void OrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseExited
           if (activeButton !=OrderButton) {
        setInitialBtnColor(OrderButton);
    }
    }//GEN-LAST:event_OrderButtonMouseExited

    private void SupplierButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierButtonMouseExited
            if (activeButton != SupplierButton) {
        setInitialBtnColor(SupplierButton);
    }
          
          
    }//GEN-LAST:event_SupplierButtonMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtContractTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractTitleActionPerformed

    private void txtContractIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractIdActionPerformed

    private void txtContractLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractLocationActionPerformed

    private void txtContractExpectedEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractExpectedEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractExpectedEndDateActionPerformed

    private void txtContractStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractStatusActionPerformed

    private void txtContractValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractValueActionPerformed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void addContractBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addContractBtnMouseClicked
        loadScreen("ContractScreen");
        setActiveButton(ContractButton);
    }//GEN-LAST:event_addContractBtnMouseClicked

    private void addContractBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addContractBtnMouseEntered
        // TODO add your handling code here:
     
      addContractBtn.setBackground( new Color(44,44,44));
    }//GEN-LAST:event_addContractBtnMouseEntered

    private void addContractBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addContractBtnMouseExited
        // TODO add your handling code here:
      addContractBtn.setBackground( Color.WHITE);
    }//GEN-LAST:event_addContractBtnMouseExited

    private void addProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseEntered
        // TODO add your handling code here:
        addProductBtn.setBackground( new Color(194,72,34));
    }//GEN-LAST:event_addProductBtnMouseEntered

    private void addProductBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseClicked
        // TODO add your handling code here:
          loadScreen("ProductScreen");
        setActiveButton(ProductButton);
    }//GEN-LAST:event_addProductBtnMouseClicked

    private void addProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseExited
        // TODO add your handling code here:
        addProductBtn.setBackground( Color.WHITE);
    }//GEN-LAST:event_addProductBtnMouseExited

    private void addStockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStockBtnMouseClicked
        // TODO add your handling code here:
        loadScreen("InStockScreen");
        setActiveButton(InStockButton);
    }//GEN-LAST:event_addStockBtnMouseClicked

    private void addStockBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStockBtnMouseEntered
        // TODO add your handling code here:
        addStockBtn.setBackground( new Color(56,183,53));
    }//GEN-LAST:event_addStockBtnMouseEntered

    private void addStockBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStockBtnMouseExited
       addStockBtn.setBackground( Color.WHITE);
    }//GEN-LAST:event_addStockBtnMouseExited

    private void addContractBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addContractBtn1MouseClicked
        int conractId = Integer.parseInt(txtContractId.getText());
        String contractTitle=txtContractTitle.getText();
        String contractLocation=txtContractLocation.getText();
        String startDateString = txtContractStartDate.getText(); 
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd"); 
        LocalDate contractStartDate = LocalDate.parse(startDateString, formatter);
        String endDateString = txtContractExpectedEndDate.getText(); 
        LocalDate contractExpectedEndDate = LocalDate.parse(endDateString, formatter);
        String contractStatus=txtContractStatus.getText();
        int contractValue=Integer.parseInt(txtContractValue.getText());
        String clientName=txtClientName.getName();
        String ScopeOfWork=txtScopeOfWork.getName();
        
    
            
        
        
    }//GEN-LAST:event_addContractBtn1MouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContractButton;
    private javax.swing.JScrollPane ContractPanel;
    private javax.swing.JLabel ContractText;
    private javax.swing.JPanel DashBoardButton;
    private javax.swing.JScrollPane DashBoardPanel;
    private javax.swing.JPanel DashBoardScreen;
    private javax.swing.JLabel DashboardText;
    private javax.swing.JPanel InStockButton;
    private javax.swing.JLabel InStockText;
    private javax.swing.JScrollPane InstockPanel;
    private javax.swing.JLabel MainLogo;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JLabel MenuIcon2;
    private javax.swing.JLabel MenuIcon3;
    private javax.swing.JLabel MenuIcon4;
    private javax.swing.JLabel MenuIcon5;
    private javax.swing.JLabel MenuIcon6;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel NewOrdersDisplayPanel;
    private javax.swing.JPanel NewOrdersDisplayPanel1;
    private javax.swing.JPanel OrderButton;
    private javax.swing.JLabel OrderText;
    private javax.swing.JScrollPane OrdersPanel;
    private javax.swing.JPanel PendingContractsDisplay1;
    private javax.swing.JPanel PendingContractsDisplay2;
    private javax.swing.JPanel ProductButton;
    private javax.swing.JScrollPane ProductPanel;
    private javax.swing.JLabel ProductText;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JPanel SupplierButton;
    private javax.swing.JLabel SupplierText;
    private javax.swing.JScrollPane SuppliersPanel;
    private javax.swing.JPanel addContractBtn;
    private javax.swing.JPanel addContractBtn1;
    private javax.swing.JLabel addContractText;
    private javax.swing.JPanel addContractsPanel;
    private javax.swing.JPanel addProductBtn;
    private javax.swing.JLabel addProductText;
    private javax.swing.JLabel addProductText1;
    private javax.swing.JLabel addProductText2;
    private javax.swing.JLabel addProductText3;
    private javax.swing.JPanel addStockBtn;
    private javax.swing.JPanel displayPanel1;
    private javax.swing.JPanel displayPanel2;
    private javax.swing.JPanel displayPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlContractMain;
    private javax.swing.JPanel pnlDataDisplayParent;
    private javax.swing.JPanel pnlDataDisplayParent1;
    private javax.swing.JPanel pnlDisplayParent;
    private javax.swing.JLabel revenueText3;
    private javax.swing.JLabel revenueText5;
    private javax.swing.JLabel revenueText6;
    private javax.swing.JTable tableContractDashboard;
    private javax.swing.JTable tableContractDashboard1;
    private javax.swing.JLabel totalPurchaseText;
    private javax.swing.JLabel totalPurchaseText1;
    private javax.swing.JLabel totalPurchaseText2;
    private javax.swing.JLabel totalPurchaseText3;
    private javax.swing.JLabel totalPurchaseText4;
    private javax.swing.JLabel totalPurchaseText5;
    private javax.swing.JLabel totalPurchaseText6;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtContractExpectedEndDate;
    private javax.swing.JTextField txtContractId;
    private javax.swing.JTextField txtContractLocation;
    private javax.swing.JTextField txtContractStatus;
    private javax.swing.JTextField txtContractTitle;
    private javax.swing.JTextField txtContractValue;
    private javax.swing.JTextArea txtScopeOfWork;
    // End of variables declaration//GEN-END:variables


class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
class RoundedTextField extends JTextField {
    private int cornerRadius = 15;
    private Color backgroundColor;

    public RoundedTextField(int columns, int radius) {
        super(columns);
        this.cornerRadius = radius;
        setOpaque(false); // To enable custom background drawing
    }

    public RoundedTextField(int columns, int radius, Color bgColor) {
        super(columns);
        this.cornerRadius = radius;
        this.backgroundColor = bgColor;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D graphics = (Graphics2D) g.create();
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Fill the rounded background
        if (backgroundColor != null) {
            graphics.setColor(backgroundColor);
        } else {
            graphics.setColor(getBackground());
        }
        
        // Adjust padding to prevent overlap
        graphics.fillRoundRect(1, 1, getWidth() - 2, getHeight() - 2, cornerRadius, cornerRadius);

        // Draw border
        graphics.setColor(getForeground());
        graphics.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, cornerRadius, cornerRadius);

        graphics.dispose();
        super.paintComponent(g);
    }

    @Override
    protected void paintBorder(Graphics g) {
        // Custom border already painted
    }

    @Override
    public void setBorder(Border border) {
        // Disable default border setting
    }
}
}

